"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, Appointment, errorMessage, getResults, Service, Status } from "../lib/api";

const statuses: Status[] = ["Pending", "Confirmed", "Completed", "Cancelled"];
const money = (number: number) => `NPR ${number.toLocaleString("en-IN")}`;
const statusStyle: Record<Status, string> = { Pending: "bg-amber-50 text-amber-700", Confirmed: "bg-blue-50 text-blue-700", Completed: "bg-emerald-50 text-emerald-700", Cancelled: "bg-gray-100 text-gray-600" };

export default function DashboardPage() {
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<"appointments" | "services">("appointments");
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("All");
  const [date, setDate] = useState("");
  const [bookingOpen, setBookingOpen] = useState(false);
  const [serviceOpen, setServiceOpen] = useState(false);
  const [editing, setEditing] = useState<Service | null>(null);
  const [message, setMessage] = useState("");
  const [formError, setFormError] = useState("");
  const [booking, setBooking] = useState({ customer_name: "", customer_phone: "", service_ids: [] as number[], appointment_date: "", appointment_time: "", notes: "" });
  const [serviceForm, setServiceForm] = useState({ name: "", price: "", duration: "" });
  const servicesQuery = useQuery({ queryKey: ["services"], queryFn: async () => getResults<Service>((await api.get("/services")).data) });
  const appointmentsQuery = useQuery({ queryKey: ["appointments"], queryFn: async () => getResults<Appointment>((await api.get("/appointments")).data) });
  const services = servicesQuery.data ?? [];
  const appointments = appointmentsQuery.data ?? [];
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ["services"] }), queryClient.invalidateQueries({ queryKey: ["appointments"] })]);
  const notify = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(""), 3000); };
  const fail = (error: unknown) => setFormError(errorMessage(error));

  const createAppointment = useMutation({ mutationFn: () => api.post("/appointments", booking), onSuccess: async () => { await refresh(); setBookingOpen(false); setBooking({ customer_name: "", customer_phone: "", service_ids: [], appointment_date: "", appointment_time: "", notes: "" }); notify("Appointment created."); }, onError: fail });
  const changeStatus = useMutation({ mutationFn: ({ id, value }: { id: number; value: Status }) => api.patch(`/appointments/${id}/status`, { status: value }), onSuccess: async () => { await refresh(); notify("Appointment status updated."); }, onError: (error) => notify(errorMessage(error)) });
  const deleteAppointment = useMutation({ mutationFn: (id: number) => api.delete(`/appointments/${id}`), onSuccess: async () => { await refresh(); notify("Appointment deleted."); }, onError: (error) => notify(errorMessage(error)) });
  const saveService = useMutation({ mutationFn: () => editing ? api.put(`/services/${editing.id}`, { name: serviceForm.name, price: Number(serviceForm.price), duration: Number(serviceForm.duration) }) : api.post("/services", { name: serviceForm.name, price: Number(serviceForm.price), duration: Number(serviceForm.duration) }), onSuccess: async () => { await refresh(); setServiceOpen(false); notify(editing ? "Service updated." : "Service added."); }, onError: fail });
  const deleteService = useMutation({ mutationFn: (id: number) => api.delete(`/services/${id}`), onSuccess: async () => { await refresh(); notify("Service deleted."); }, onError: (error) => notify(errorMessage(error)) });

  const filtered = useMemo(() => appointments.filter((item) => `${item.customer_name} ${item.customer_phone}`.toLowerCase().includes(search.toLowerCase()) && (status === "All" || item.status === status) && (!date || item.appointment_date === date)), [appointments, search, status, date]);
  const bookingServices = services.filter((service) => booking.service_ids.includes(service.id));
  const isLoading = servicesQuery.isLoading || appointmentsQuery.isLoading;
  const apiError = servicesQuery.error || appointmentsQuery.error;
  const selectService = (id: number) => setBooking((current) => ({ ...current, service_ids: current.service_ids.includes(id) ? current.service_ids.filter((serviceId) => serviceId !== id) : [...current.service_ids, id] }));
  const submitBooking = (event: FormEvent) => { event.preventDefault(); setFormError(""); if (!booking.customer_name.trim() || !booking.customer_phone.trim() || !booking.service_ids.length || !booking.appointment_date || !booking.appointment_time) return setFormError("Customer, phone, at least one service, date, and time are required."); createAppointment.mutate(); };
  const openService = (service?: Service) => { setFormError(""); setEditing(service ?? null); setServiceForm(service ? { name: service.name, price: String(service.price), duration: String(service.duration) } : { name: "", price: "", duration: "" }); setServiceOpen(true); };
  const submitService = (event: FormEvent) => { event.preventDefault(); setFormError(""); if (!serviceForm.name.trim() || Number(serviceForm.price) <= 0 || Number(serviceForm.duration) <= 0) return setFormError("Enter a service name, positive price, and duration."); saveService.mutate(); };
  const revenue = appointments.filter((item) => item.status !== "Cancelled").reduce((total, item) => total + (item.total_price ?? item.services.reduce((sum, service) => sum + service.price, 0)), 0);

  return <div className="min-h-screen bg-[#f8faf9] text-gray-900">
    <header className="border-b border-gray-100 bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#2C7A6E] font-bold text-white">S</span><b className="text-lg">SalonBook</b><span className="hidden border-l border-gray-200 pl-2.5 text-sm text-gray-400 sm:block">Staff portal</span></Link><span className="text-sm text-gray-500">Salon Team</span></div></header>
    <main className="mx-auto max-w-7xl px-5 py-8 lg:px-8 lg:py-10">
      {message && <div role="status" className="fixed right-5 top-20 z-50 max-w-sm rounded-xl bg-[#236258] px-4 py-3 text-sm text-white shadow-lg">{message}</div>}
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#2C7A6E]">Staff workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Salon appointments</h1><p className="mt-2 text-sm text-gray-500">Manage bookings and services from one place.</p></div><button onClick={() => { setFormError(""); setBookingOpen(true); }} className="button-primary">+ New appointment</button></div>
      {apiError ? <ErrorState text={errorMessage(apiError)} retry={() => { servicesQuery.refetch(); appointmentsQuery.refetch(); }} /> : isLoading ? <div className="mt-8 rounded-2xl border border-gray-100 bg-white p-12 text-center text-sm text-gray-500">Loading salon data…</div> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Appointments" value={String(appointments.length)} /><Stat label="Pending" value={String(appointments.filter((item) => item.status === "Pending").length)} /><Stat label="Services" value={String(services.length)} /><Stat label="Booking value" value={money(revenue)} /></section>
      <div className="mt-9 flex gap-6 border-b border-gray-200"><button onClick={() => setTab("appointments")} className={`border-b-2 pb-3 text-sm font-semibold ${tab === "appointments" ? "border-[#2C7A6E] text-[#2C7A6E]" : "border-transparent text-gray-500"}`}>Appointments</button><button onClick={() => setTab("services")} className={`border-b-2 pb-3 text-sm font-semibold ${tab === "services" ? "border-[#2C7A6E] text-[#2C7A6E]" : "border-transparent text-gray-500"}`}>Services</button></div>
      {tab === "appointments" ? <section className="mt-6 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-gray-100 p-5 lg:flex-row lg:justify-between"><div><h2 className="font-semibold">Appointments</h2><p className="mt-1 text-sm text-gray-500">Each booking shows all selected services.</p></div><div className="flex flex-col gap-2 sm:flex-row"><input className="rounded-lg border border-gray-200 px-3 py-2 text-sm" placeholder="Search customer or phone" value={search} onChange={(event) => setSearch(event.target.value)} /><select className="rounded-lg border border-gray-200 px-3 py-2 text-sm" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select><input className="rounded-lg border border-gray-200 px-3 py-2 text-sm" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div></div><AppointmentTable appointments={filtered} statusChange={(id, value) => changeStatus.mutate({ id, value })} remove={(id) => deleteAppointment.mutate(id)} /></section> : <Services services={services} add={() => openService()} edit={openService} remove={(id) => deleteService.mutate(id)} />}</>}
    </main>
    {bookingOpen && <Modal title="New appointment" close={() => setBookingOpen(false)}><form onSubmit={submitBooking} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Customer name *"><input required className="input" value={booking.customer_name} onChange={(event) => setBooking({ ...booking, customer_name: event.target.value })} /></Field><Field label="Phone number *"><input required className="input" value={booking.customer_phone} onChange={(event) => setBooking({ ...booking, customer_phone: event.target.value })} /></Field></div><div><p className="mb-2 text-sm font-medium text-gray-700">Services *</p><div className="grid gap-2 sm:grid-cols-2">{services.map((service) => <button type="button" key={service.id} onClick={() => selectService(service.id)} className={`flex justify-between rounded-xl border p-3 text-left text-sm ${booking.service_ids.includes(service.id) ? "border-[#2C7A6E] bg-[#eaf4f2]" : "border-gray-200"}`}><span><b className="block">{service.name}</b><small className="text-gray-500">{service.duration} min</small></span><b className="text-[#2C7A6E]">{money(service.price)}</b></button>)}</div>{bookingServices.length > 0 && <p className="mt-2 text-xs font-medium text-[#2C7A6E]">{bookingServices.length} selected · {money(bookingServices.reduce((total, service) => total + service.price, 0))}</p>}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="Date *"><input type="date" required className="input" value={booking.appointment_date} onChange={(event) => setBooking({ ...booking, appointment_date: event.target.value })} /></Field><Field label="Time *"><input type="time" required className="input" value={booking.appointment_time} onChange={(event) => setBooking({ ...booking, appointment_time: event.target.value })} /></Field></div><Field label="Notes"><textarea className="input min-h-20 resize-none" value={booking.notes} onChange={(event) => setBooking({ ...booking, notes: event.target.value })} /></Field><FormError text={formError} /><Actions close={() => setBookingOpen(false)} label="Create appointment" loading={createAppointment.isPending} /></form></Modal>}
    {serviceOpen && <Modal title={editing ? "Edit service" : "Add service"} close={() => setServiceOpen(false)}><form onSubmit={submitService} className="space-y-4"><Field label="Service name *"><input required className="input" value={serviceForm.name} onChange={(event) => setServiceForm({ ...serviceForm, name: event.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Price (NPR) *"><input required min="1" type="number" className="input" value={serviceForm.price} onChange={(event) => setServiceForm({ ...serviceForm, price: event.target.value })} /></Field><Field label="Duration (minutes) *"><input required min="1" type="number" className="input" value={serviceForm.duration} onChange={(event) => setServiceForm({ ...serviceForm, duration: event.target.value })} /></Field></div><FormError text={formError} /><Actions close={() => setServiceOpen(false)} label={editing ? "Save changes" : "Add service"} loading={saveService.isPending} /></form></Modal>}
  </div>;
}

function AppointmentTable({ appointments, statusChange, remove }: { appointments: Appointment[]; statusChange: (id: number, value: Status) => void; remove: (id: number) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead className="bg-gray-50 text-xs uppercase tracking-wider text-gray-400"><tr><th className="px-5 py-3.5">Customer</th><th className="px-5 py-3.5">Services</th><th className="px-5 py-3.5">Date & time</th><th className="px-5 py-3.5">Status</th><th className="px-5 py-3.5 text-right">Action</th></tr></thead><tbody className="divide-y divide-gray-100">{appointments.map((appointment) => { const duration = appointment.total_duration ?? appointment.services.reduce((total, service) => total + service.duration, 0); const price = appointment.total_price ?? appointment.services.reduce((total, service) => total + service.price, 0); return <tr key={appointment.id}><td className="px-5 py-4"><b className="text-sm">{appointment.customer_name}</b><p className="mt-0.5 text-xs text-gray-400">{appointment.customer_phone}</p></td><td className="px-5 py-4"><div className="flex max-w-64 flex-wrap gap-1.5">{appointment.services.map((service) => <span key={service.id} className="rounded-md bg-[#eaf4f2] px-2 py-1 text-xs font-semibold text-[#236258]">{service.name}</span>)}</div><p className="mt-1.5 text-xs text-gray-400">{duration} min · {money(price)}</p></td><td className="px-5 py-4 text-sm text-gray-600"><p>{appointment.appointment_date}</p><p className="mt-0.5 text-xs text-gray-400">{appointment.appointment_time}</p></td><td className="px-5 py-4"><select className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusStyle[appointment.status]}`} value={appointment.status} onChange={(event) => statusChange(appointment.id, event.target.value as Status)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></td><td className="px-5 py-4 text-right"><button onClick={() => remove(appointment.id)} className="text-sm text-gray-400 hover:text-red-600">Delete</button></td></tr>; })}{!appointments.length && <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-gray-400">No appointments found.</td></tr>}</tbody></table></div>; }
function Services({ services, add, edit, remove }: { services: Service[]; add: () => void; edit: (service: Service) => void; remove: (id: number) => void }) { return <section className="mt-6 rounded-2xl border border-gray-100 bg-white shadow-sm"><div className="flex justify-between border-b border-gray-100 p-5"><div><h2 className="font-semibold">Salon services</h2><p className="mt-1 text-sm text-gray-500">Services available for booking.</p></div><button onClick={add} className="button-primary">+ Add service</button></div>{services.map((service) => <div key={service.id} className="flex items-center justify-between border-b border-gray-100 p-5"><div><b>{service.name}</b><p className="text-sm text-gray-500">{service.duration} minutes · {money(service.price)}</p></div><div className="flex gap-4 text-sm"><button onClick={() => edit(service)} className="text-[#2C7A6E]">Edit</button><button onClick={() => remove(service.id)} className="text-gray-400 hover:text-red-600">Delete</button></div></div>)}</section>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-4 text-2xl font-bold">{value}</p></div>; }
function ErrorState({ text, retry }: { text: string; retry: () => void }) { return <div role="alert" className="mt-8 rounded-2xl border border-red-100 bg-red-50 p-6 text-red-800"><b>Couldn&apos;t load salon data</b><p className="mt-1 text-sm">{text}</p><button onClick={retry} className="mt-4 rounded-lg bg-white px-3 py-2 text-sm font-semibold text-red-700">Try again</button></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-40 flex items-center justify-center bg-gray-900/30 p-4"><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={close} aria-label="Close" className="text-gray-400">✕</button></div>{children}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-gray-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function FormError({ text }: { text: string }) { return text ? <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{text}</p> : null; }
function Actions({ close, label, loading }: { close: () => void; label: string; loading: boolean }) { return <div className="flex justify-end gap-3 border-t border-gray-100 pt-5"><button className="button-secondary" type="button" onClick={close}>Cancel</button><button disabled={loading} className="button-primary disabled:opacity-60">{loading ? "Saving…" : label}</button></div>; }
